# Generated by Django 6.0.5 on 2026-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chercheur_projetrecherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
