# Generated by Django 6.0.5 on 2026-06-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('panne', 'En panne'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], max_length=20)),
                ('availability', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('utilise', 'En cours d’utilisation'), ('indisponible', 'Indisponible')], max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
