# Generated by Django 6.0.5 on 2026-06-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterielRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('laboratoire', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Matériel de recherche',
                'verbose_name_plural': 'Matériels de recherche',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ReservationMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur', models.CharField(max_length=120)),
                ('email_demandeur', models.EmailField(max_length=254)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.materielrecherche')),
            ],
            options={
                'verbose_name': 'Réservation de matériel',
                'verbose_name_plural': 'Réservations de matériels',
                'ordering': ['-date_debut'],
            },
        ),
    ]
